<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit01d3b6eb1be1760b78130560ec760831
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'EasyScss\\Shared\\' => 16,
            'EasyScss\\Public\\' => 16,
            'EasyScss\\Languages\\' => 19,
            'EasyScss\\Admin\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'EasyScss\\Shared\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
        'EasyScss\\Public\\' => 
        array (
            0 => __DIR__ . '/../..' . '/public',
        ),
        'EasyScss\\Languages\\' => 
        array (
            0 => __DIR__ . '/../..' . '/languages',
        ),
        'EasyScss\\Admin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/admin',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'EasyScss\\Admin\\EasyScssAdmin' => __DIR__ . '/../..' . '/admin/EasyScssAdmin.php',
        'EasyScss\\Public\\EasyScssPublic' => __DIR__ . '/../..' . '/public/EasyScssPublic.php',
        'EasyScss\\Shared\\EasyScss' => __DIR__ . '/../..' . '/includes/EasyScss.php',
        'EasyScss\\Shared\\EasyScssActivator' => __DIR__ . '/../..' . '/includes/EasyScssActivator.php',
        'EasyScss\\Shared\\EasyScssDeactivator' => __DIR__ . '/../..' . '/includes/EasyScssDeactivator.php',
        'EasyScss\\Shared\\EasyScssGlobals' => __DIR__ . '/../..' . '/includes/EasyScssGlobals.php',
        'EasyScss\\Shared\\EasyScssLoader' => __DIR__ . '/../..' . '/includes/EasyScssLoader.php',
        'EasyScss\\Shared\\EasyScssLocale' => __DIR__ . '/../..' . '/includes/EasyScssLocale.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit01d3b6eb1be1760b78130560ec760831::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit01d3b6eb1be1760b78130560ec760831::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit01d3b6eb1be1760b78130560ec760831::$classMap;

        }, null, ClassLoader::class);
    }
}
