<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'EasyScss\\Admin\\EasyScssAdmin' => $baseDir . '/admin/EasyScssAdmin.php',
    'EasyScss\\Public\\EasyScssPublic' => $baseDir . '/public/EasyScssPublic.php',
    'EasyScss\\Shared\\EasyScss' => $baseDir . '/includes/EasyScss.php',
    'EasyScss\\Shared\\EasyScssActivator' => $baseDir . '/includes/EasyScssActivator.php',
    'EasyScss\\Shared\\EasyScssDeactivator' => $baseDir . '/includes/EasyScssDeactivator.php',
    'EasyScss\\Shared\\EasyScssGlobals' => $baseDir . '/includes/EasyScssGlobals.php',
    'EasyScss\\Shared\\EasyScssLoader' => $baseDir . '/includes/EasyScssLoader.php',
    'EasyScss\\Shared\\EasyScssLocale' => $baseDir . '/includes/EasyScssLocale.php',
);
