<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'EasyScss\\Shared\\' => array($baseDir . '/includes'),
    'EasyScss\\Public\\' => array($baseDir . '/public'),
    'EasyScss\\Languages\\' => array($baseDir . '/languages'),
    'EasyScss\\Admin\\' => array($baseDir . '/admin'),
);
